apiVersion: v2
version: 1.0.0
name: ttt-match-management
dependencies:
  - name: generic-chart
    version: 2.0.0
    repository: https://registry.baloise.dev/chartrepo/library
    alias: management-backend
  - name: generic-chart
    version: 2.0.0
    repository: https://registry.baloise.dev/chartrepo/library
    alias: admin-view
  - name: generic-chart
    version: 2.0.0
    repository: https://registry.baloise.dev/chartrepo/library
    alias: mysql-db
