mysql-db:
  image:
    repository: holzleube/mysql-docker-image
    tag: "4.2"
  auth:
    username: ttv
    passwort: test1234
    rootPassword: test12345
  primary:
    podSecurityContext:
      enabled: false
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false
  volumePermissions:
    enabled: true
management-backend:
  replicaCount: 1
  image:
    repository: holzleube/turniermanager
    tag: 3.7
  network:
    http:
      servicePort: 80
      containerPort: 9000
      ingress:
        host: ttt-management.apps.okd.baloise.dev
        path: /api
  env:
    - name: MYSQL_JDBC
      value: "jdbc:mysql://ttt-match-management-mysql-db:3306/tournamentManager"
    - name: MYSQL_PW
      value: test12345
    - name: MYSQL_USER
      value: root
  resources:
    requests:
      memory: 1Gi
      cpu: 2
    limits:
      memory: 2Gi
      cpu: 4
admin-view:
  replicaCount: 1
  image:
    repository: holzleube/tt-admin-view
    tag: e7ba27fbcd9a437b9e48a024825c4fd49f8c96f7
    pullPolicy: Always
  network:
    http:
      ingress:
        host: ttt-management.apps.baloise.dev
  resources:
    requests:
      memory: 1Mi
    limits:
      memory: 100Mi
