mysql-db:
  image:
    repository: holzleube/mysql-docker-image
    tag: "4.0"
  auth:
    username: ttv
    passwort: test1234
  primary:
    containerSecurityContext:
      runAsUser: 1001560001
    podSecurityContext:
      enabled: false
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false
management-backend:
  replicaCount: 1
  image:
    repository: holzleube/turniermanager
    tag: 3.4
  network:
    http:
      servicePort: 9000
      ingress:
        host: ttt-management.apps.okd.baloise.dev
        path: /api
  env:
    - name: MYSQL_JDBC
      value: "jdbc:mysql://ttt-match-management-mysql-db:3306/tournamentManager"
    - name: MYSQL_PW
      value: test1234
    - name: MYSQL_USER
      value: ttv
  resources:
    requests:
      memory: 1Gi
      cpu: 2
    limits:
      memory: 2Gi
      cpu: 4
admin-view:
  replicaCount: 1
  image:
    repository: holzleube/tt-admin-view
    tag: main
  network:
    http:
      servicePort: 80
      ingress:
        host: ttt-management.apps.baloise.dev
  resources:
    requests:
      memory: 1Mi
    limits:
      memory: 100Mi
