mysql-db:
  replicaCount: 1
  image:
    repository: holzleube/mysql-docker-image
    tag: 4.0
  service:
    type: ClusterIP
  env:
    - name: MYSQL_ROOT_PASSWORD
      value: mysecretpassword
  network:
    http:
      containerPort: 3306
      servicePort: 3306
  resources:
    requests:
      memory: 1Mi
    limits:
      memory: 100Mi
management-backend:
  replicaCount: 1
  image:
    repository: holzleube/turniermanager
    tag: 3.2
  network:
    http:
      containerPort: 9000
      servicePort: 9000
      ingress:
        host: ttt-management.apps.okd.baloise.dev
        path: /api
  service:
    type: ClusterIP
  env:
    - name: MYSQL_SERVER
      value: mysql-db
    - name: MYSQL_DB
      value: tournamentManager
    - name: MYSQL_USER
      value: root
    - name: MYSQL_PORT
      value: 3306
    - name: MYSQL_PW
      value: mysecretpassword
  resources:
    requests:
      memory: 1Mi
    limits:
      memory: 100Mi

admin-view:
  replicaCount: 1
  image:
    repository: holzleube/tt-admin-view
    tag: main
  network:
    http:
      servicePort: 80
      ingress:
        host: ttt-management.apps.baloise.dev
  service:
    type: ClusterIP
  resources:
    requests:
      memory: 1Mi
    limits:
      memory: 100Mi
