app:
  frontend:
    replicaCount: 1
    appPort: 8080
    image:
      repository: tabletennistournament/match-management-client
      tag: client-build-speed-abd9a17
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 80
    route:
      enabled: true
      path: /
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
  backend:
    replicaCount: 1
    appPort: 8080
    livenessProbePath: api/actuator/health
    readinessProbePath: api/actuator/health
    image:
      repository: tabletennistournament/match-management-server
      tag: master
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 80
    route:
      enabled: true
      path: /api
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
  postgresql:
    enabled: true
    databaseName: app
    user: postgresql
    password: postgresql
    image:
      repository: centos/postgresql-96-centos7
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 5432
    persistence:
      enabled: true
      stroageClass: rook-ceph-block
      size: 1Gi
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
