{{- range $key, $value := .Values.applications -}}
{{- $namespace := $key -}}
{{- if not (kindIs "invalid" .namespace) -}}
{{- $namespace = .namespace }}
{{- end -}}
{{- if or ((kindIs "invalid" $value.enabled)) $value.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  namespace: argocd
spec:
  destination:
    namespace: {{ default $key $value.namespace }}
    server: {{ $.Values.server }}
  project: {{ $.Values.project }}
  {{- if .ignoreDifferences }}
  ignoreDifferences:
  {{- toYaml .ignoreDifferences | nindent 4 }}
  {{ end }}
  source:
{{- if $value.helm }}
    helm:
{{- toYaml $value.helm | nindent 6 -}}
{{- end -}}
{{- if $value.kustomize }}
    kustomize:
  {{- toYaml $value.kustomize | nindent 6 -}}
{{- end }}
    path: {{ $namespace }}
    repoURL: {{ $.Values.repoURL }}
    targetRevision: {{ default "HEAD" $value.targetRevision }}
  {{- if $value.syncPolicy }}
  syncPolicy:
  {{- toYaml $value.syncPolicy | nindent 4 }}
{{- end }}
{{ end }}
{{- end }}