{{- range .Values.applications -}}
{{- $namespace := .name -}}
{{- if not (kindIs "invalid" .namespace) -}}
{{- $namespace = .namespace }}
{{- end -}}
{{- if or ((kindIs "invalid" .enabled)) .enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  destination:
    namespace: {{ default .name .namespace }}
    server: {{ $.Values.server }}
  project: {{ $.Values.project }}
  {{- if .ignoreDifferences }}
  ignoreDifferences:
  {{- toYaml .ignoreDifferences | nindent 4 }}
  {{ end }}
  source:
{{- if .helm }}
    helm:
{{- toYaml .helm | nindent 6 -}}
{{- end -}}
{{- if .kustomize }}
    kustomize:
  {{- toYaml .kustomize | nindent 6 -}}
{{- end }}
    path: {{ $namespace }}
    repoURL: {{ $.Values.repoURL }}
    targetRevision: {{ default "HEAD" .targetRevision }}
  {{- if .syncPolicy }}
  syncPolicy:
  {{- toYaml .syncPolicy | nindent 4 }}
{{- end }}
{{ end }}
{{- end }}