{{- range $key, $value := .Values.applications -}}
{{- if not .noNamespaceCreation -}}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: {{ default "" $value.description | quote }}
    openshift.io/display-name: {{ default "" $value.displayName | quote }}
    openshift.io/requester: {{ default "" $.Values.requestor | quote }}
{{- if not (kindIs "invalid" $value.idRange) }}   
    openshift.io/sa.scc.supplemental-groups: {{ $value.idRange }}
    openshift.io/sa.scc.uid-range:  {{ $value.idRange }}
{{ end }}
  name: {{ default $key $value.namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ default $key $value.namespace | quote }}
  name: table-tennis-tournament
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: Group
  name: "table-tennis-tournament" 
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{ end }}