{{- if .Values.route.enabled -}}
{{- $fullName := include "app.fullname" . -}}
{{- $defaultUrl := printf "%s.%s" .Release.Name $.Values.route.defaultDomain -}}
{{- $routePath := .Values.backend.route.path -}}
{{- $host := .Values.route.host -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ template "app.name" . }}-backend
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ $fullName }}-backend
spec:
  host: {{ default $defaultUrl $host }}
  path: {{ $routePath }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ template "app.fullname" . }}-backend
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - routerName: router
{{- end }}