apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}-backend
  labels:
    app: {{ template "app.name" . }}-backend
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}-backend
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}-backend
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.appPort }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 3
            httpGet:
              path: {{ .Values.backend.livenessProbePath }}
              port: {{ .Values.backend.appPort }}
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 3
            httpGet:
              path: {{ .Values.backend.readinessProbePath }}
              port: {{ .Values.backend.appPort }}
          resources:
{{ toYaml .Values.backend.resources | indent 12 }}
    {{- with .Values.backend.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.backend.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.backend.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
