{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}-postgresql
  labels:
    app: {{ template "app.name" . }}-postgresql
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: 5432
      protocol: TCP
  selector:
    app: {{ template "app.name" . }}-postgresql
    release: {{ .Release.Name }}
{{- end }}
