{{- if .Values.postgresql.enabled -}}
{{- $host := printf "%s-%s" (include "app.fullname" . ) "postgresql" -}}
apiVersion: v1
data:
  database-name: {{ .Values.postgresql.databaseName | b64enc }}
  database-password: {{ .Values.postgresql.password | b64enc }}
  database-user: {{ .Values.postgresql.user | b64enc }}
  database-host: {{ $host | b64enc }}
kind: Secret
metadata:
  labels:
    app: {{ template "app.name" . }}-postgresql
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "app.name" . }}-postgresql
type: Opaque
{{- end}}