route:
  enabled: true
  host: ""
  defaultDomain: apps.wheel.sh

postgresql:
  enabled: true
  databaseName: app
  user: postgresql
  password: postgresql
  image:
    repository: centos/postgresql-96-centos7
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432
  persistence:
    enabled: true
    storageClass: rook-ceph-block
    size: 1Gi
  resources: {}
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
  #  memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

frontend:
  replicaCount: 1
  appPort: 8080
  image:
    repository: tabletennistournament/match-management-client
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  route:
    path: /
  resources: {}
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

backend:
  replicaCount: 1
  appPort: 8080
  image:
    repository: tabletennistournament/match-management-server
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  route:
    path: /api
  livenessProbePath: api/hello
  readinessProbePath: api/hello
  resources: {}
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}