app:
  frontend:
    replicaCount: 1
    appPort: 8080
    image:
      repository: tabletennistournament/match-management-client
      tag: master-9233341
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 80
    route:
      enabled: true
      path: /
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
  backend:
    replicaCount: 1
    appPort: 8080
    livenessProbePath: api/actuator/health
    readinessProbePath: api/actuator/health
    image:
      repository: tabletennistournament/match-management-server
      tag: master-89680cb
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 80
    route:
      enabled: true
      path: /api
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
