app:
  frontend:
    replicaCount: 1
    appPort: 8080
    image:
      repository: tabletennistournament/match-management-client
      tag: feature-test-kup-911f6cb
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 80
    route:
      enabled: true
      path: /
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
  backend:
    replicaCount: 1
    appPort: 8080
    livenessProbePath: api/hello
    readinessProbePath: api/hello
    image:
      repository: tabletennistournament/match-management-server
      tag: master
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 80
    route:
      enabled: true
      path: /api
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
