namespaces:
  users:
  - niiku
  - christiansiegel
  - joachimprinzbach
  - leubedane
  - dane@nikio.io
  - kullmanp
  - luechtdiode
  - lennartx
  - arburk
  - yannickholzenkamp
  applications:
    ttt-match-management:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-fixes:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-fix-sorting:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
