namespaces:
  users:
  - niiku
  - christiansiegel
  - joachimprinzbach
  - leubedane
  - dane@nikio.io
  - kullmanp
  - luechtdiode
  - lennartx
  - arburk
  applications:
    ttt-match-management-feat-adjust_app_name:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
