namespaces:
  users:
  - niiku
  - christiansiegel
  - joachimprinzbach
  - leubedane
  - dane@nikio.io
  - kullmanp
  - luechtdiode
  - lennartx
  - arburk
  - yannickholzenkamp
  applications:
    ttt-match-management:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-feat-hash-routing:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-feat-player-score:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-css-improvements:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-feat-sidenav:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-feat-nginx-config:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-feat-validation-in-model:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-feat-refactorings:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-usecase4-putstate:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-feat-eventbus:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-feat-assign-match-svc:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-css-layouting:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-feat-use-case-5:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-client-build-speed:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-feat-table-match-list:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-feat-match-stage:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-feat-errors:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-feat-number-input:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-feat-display-stage:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
