namespaces:
  users:
  - niiku
  - christiansiegel
  - joachimprinzbach
  - leubedane
  - dane@nikio.io
  - kullmanp
  - luechtdiode
  - lennartx
  - arburk
  - yannickholzenkamp
  - vangual
  applications:
    ttt-match-management:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-usecase6:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-feat-ui-game-res:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-fix-travis:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-feat-awesome-colors:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
    ttt-match-management-multiple-players:
      helm:
        valueFiles:
        - values.yaml
      syncPolicy:
        automated:
          prune: true
