apiVersion: v2
version: 1.0.0
name: ttt-registration
dependencies:
  - name: generic-chart
    version: 2.3.0
    repository: https://baloise-incubator.github.io/generic-chart/
    alias: registration
  - name: mysql
    version: '9.4.1'
    repository: https://charts.bitnami.com/bitnami
    alias: mysql
