app:
  frontend:
    replicaCount: 1
    appPort: 8080
    image:
      repository: tabletennistournament/match-management-client
      tag: master
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 80
    route:
      enabled: true
      path: /
    resources: {}
      # limits:
      #  cpu: 100m
      #  memory: 128Mi
      # requests:
      #  cpu: 100m
    #  memory: 128Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}

  backend:
    replicaCount: 1
    appPort: 8080
    livenessProbePath: api/hello
    readinessProbePath: api/hello
    image:
      repository: tabletennistournament/match-management-server
      tag: master
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 80
    route:
      enabled: true
      path: /api
    resources: {}
      # limits:
      #  cpu: 100m
      #  memory: 128Mi
      # requests:
      #  cpu: 100m
    #  memory: 128Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}